### ISSUE TITLE
Problem when adding a png on fetch.json file

### ISSUE THREAD

**Issue by tcastelli** [mizzao/meteor-build-fetcher#4]
The error on #3  happens when i try to add the following to my json file
````js
 {
    "file": "/img/flags.png",
    "url": "https://raw.githubusercontent.com/Bluefieldscom/intl-tel-input/master/build/img/flags.png"
  },
  {
    "file": "/img/flags@2x.png",
    "url": "https://raw.githubusercontent.com/Bluefieldscom/intl-tel-input/master/build/img/flags%402x.png"
  }
````

and run meteor for the second time(initially i thought it was because of debug mode, but it happens also in normal runs, here is the log:
````js
 While processing files with mizzao:build-fetcher (for target
   web.browser):
   C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:387:15:
   'data' option to addAsset must be a Buffer or String.
   at [object Object]._.extend.addAsset (C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:387:15)
   at [object Object]._.extend.addAsset (C:\Users\xxxx\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\tools\isobuild\compiler-plugin.js:277:24)
   at Fetcher.addCompileResult (<runJavaScript-51>:135:27)
   at <runJavaScript-50>:352:16
   at C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:182:20
   at replenish (C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:317:21)
   at C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:328:15
   at Object.async.forEachLimit.async.eachLimit (C:\Users\xxxx\AppData\Local\.meteor\packages\mizzao_build-fetcher\0.3.1\plugin.fetcher.os\npm\caching-compiler\node_modules\async\lib\async.js:221:35)
   at Fetcher.processFilesForTarget (<runJavaScript-50>:324:11)
````

I guess it could be because api.addAssets has to be used with pngs and the download with caching is not working properly (I have solved the problem in my own package downloading the png files separately and adding them with addAssets)

**Comment by mizzao** [comment]
Clearly this is a problem with the caching if it works the first time but doesn't work after that. I don't think it would be specific to `png` files. I'm guessing maybe the `Buffer` that comes with a download doesn't serialize properly and then is invalid on the second run of the app.

I will look into it when I get a moment.

**Comment by mizzao** [comment]
Okay - the issue here is that `Buffer`s are serialized to arrays of octets during the compile step and they have to be properly resurrected back to `Buffer`s in order for the caching to work properly. I have a fix and will deploy it shortly.

**Comment by tcastelli** [comment]
Good to know! :)

**Comment by mizzao** [comment]
Can you give 0.3.2 a try and see if the problem persists?
